# Generated by Django 4.2.11 on 2024-07-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='order_in_Project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
