# Generated by Django 4.2.11 on 2024-04-29 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0007_favoriteroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritesRoomsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_rooms', models.ManyToManyField(blank=True, related_name='favorite_rooms', to='taskmanager.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FavoriteRoom',
        ),
    ]
