# Generated by Django 4.2.11 on 2024-05-31 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_favoritesroomslist_delete_favoriteroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
